---
services:
  dev_container:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile

  data_reviewer-db:
    image: postgres:17.2
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: dataland_qa_lab
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:5050:80"

volumes:
  pgdata: